### ISSUE TITLE
openalex_harvest_pub task fails during results pagination

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss-labs/rialto-airflow#57]
When running with a dev_limit of 1000, the openalex_harvest_pub task sometimes fails with:

```
[2024-06-25, 18:29:26 UTC] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/rialto_airflow/dags/harvest.py", line 95, in openalex_harvest_pubs
    openalex.publications_csv(dois, csv_file)
  File "/opt/airflow/rialto_airflow/harvest/openalex.py", line 76, in publications_csv
    for pub in publications_from_dois(dois):
  File "/opt/airflow/rialto_airflow/harvest/openalex.py", line 89, in publications_from_dois
    for page in Works().filter(doi=doi_list).paginate(per_page=200):
  File "/home/airflow/.local/lib/python3.12/site-packages/pyalex/api.py", line 152, in __next__
    self._next_value = meta["next_cursor"]
                       ~~~~^^^^^^^^^^^^^^^
KeyError: 'next_cursor'
[2024-06-25, 18:29:26 UTC] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=harvest, task_id=openalex_harvest_pubs, run_id=manual__2024-06-25T17:23:53.071843+00:00, execution_date=20240625T172353, start_date=20240625T182053, end_date=20240625T182926
[2024-06-25, 18:29:26 UTC] {standard_task_runner.py:110} ERROR - Failed to execute job 61 for task openalex_harvest_pubs ('next_cursor'; 857)
[2024-06-25, 18:29:26 UTC] {local_task_job_runner.py:240} INFO - Task exited with return code 1
```

**Comment by lwrubel** [comment]
Closing since we haven't seen this in recent runs.
